NithAdministration/NithAdministration/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url




admin.site.site_header ='/static/logo.png'
admin.site.site_title = 'National Institute of Technology Kurukshetra'
admin.site.index_title = 'NITK Student Database '

urlpatterns = [
    path('', admin.site.urls),
    path('', include('Student.urls')),
    
   

]

NithAdministration/Student/urls.py
from django.urls import path

from Student import views




urlpatterns = [
    path('nith/', views.index, name='index'),
    path('guidelines/', views.guidelines, name='guidelines'),
    path('analytics/', views.staffguidelines, name='analytics'),
    
    
]

NithAdministration/Student/models.py
from django.db import models
from Address.models import District, State, Address
from django.utils import timezone
from Institution.models import Degree, Subject


class Board(models.Model):
    boardName = models.CharField(max_length=50, verbose_name='Board')

    def __str__(self):
        return self.boardName


class Category(models.Model):
    categoryName = models.CharField(max_length=30, unique=True, verbose_name='Category Name')

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.categoryName


class Activity(models.Model):
    activityName = models.CharField(max_length=30, verbose_name='Activity Name')
    startDate = models.DateField(verbose_name='Start Date')
    endDate = models.DateField(verbose_name='End Date')
    location = models.ForeignKey(District, on_delete=models.PROTECT)
    description = models.TextField(max_length=250)
    created =models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Activities'

    def __str__(self):
        return self.activityName 


class Student(models.Model):
    GENDER = [('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')]
    DEPARTMENT = [('CSE', 'CSE'), ('ECE', 'ECE'), ('MECHANICAL', 'MECHANICAL'),('CIVIL', 'CIVIL'), ('CHEMICAL', 'CHEMICAL'), ('ELECTRICAL', 'ELECTRICAL'),('PHYSICS', 'PHYSICS'), ('CHEMISTRY', 'CHEMISTRY'), ('MATHEMATICS', 'MATHEMATICS'),('MANAGEMENT', 'MANAGEMENT'), ('HUMANITIES', 'HUMANITIES'), ('ARCHITECTURE', 'ARCHITECTURE'), ('MATERIAL SCIENCE', 'MATERIAL SCIENCE'), ('ENERGY AND ENVIRONMENT', 'ENERGY AND ENVIRONMENT')]
    registrationNumber = models.CharField(max_length=30, unique=True, verbose_name='Registration Number')
    id = models.CharField(max_length=15, unique=True, verbose_name='NITH Roll Number',primary_key=True)
    jeeMainRollNumber = models.CharField(max_length=15, verbose_name='JEE Main Roll Number')
    studentName = models.CharField(max_length=80, verbose_name='Student Name',null=True)
    mothersName = models.CharField(max_length=80, verbose_name="Mother's Name")
    fathersName = models.CharField(max_length=80, verbose_name="Father's Name")
    dob = models.DateField(verbose_name='Date Of Birth')
    gender = models.CharField(max_length=80, choices=GENDER)
    bonafideState = models.ForeignKey(State, on_delete=models.PROTECT, verbose_name='Bonafide State')
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    familyIncome = models.IntegerField(blank=True, verbose_name='Family Income',null=True)
    jeeAIR = models.IntegerField(verbose_name='JEE Main All India Rank')
    jeeCategoryRank = models.IntegerField(verbose_name='JEE Main Category Rank')
    studentEmail = models.EmailField(verbose_name='Student Email')
    studentEmail_alt = models.EmailField(verbose_name='Alternate Student Email',null=True)
    studentMobileNumber = models.CharField(max_length=13, verbose_name='Student Mobile Number')
    studentMobileNumber_alt = models.CharField(max_length=13, verbose_name='Alternate Student Mobile Number',null=True)
    parentMobileNumber = models.CharField(max_length=13, verbose_name='Parent Mobile Number')
    parentMobileNumber_alt = models.CharField(max_length=13, verbose_name='Alternate Parent Mobile Number',null=True)   
    parenttEmail = models.EmailField(verbose_name='Parent Email',null=True)
    parentEmail_alt = models.EmailField(verbose_name='Alternate Parent Email',null=True)
    boarder = models.BooleanField()


    xMarks = models.FloatField(verbose_name='X Marks (Percentage) or (Grade x 9.5)')
    xBoard = models.ForeignKey(Board, on_delete=models.PROTECT, related_name='xStudents', verbose_name='X Board')
    yearOfPassingX = models.SmallIntegerField(verbose_name='Year Of Passing X')

    xiiMarks = models.FloatField(verbose_name='XII Marks (Percentage) or (Grade x 9.5)')
    xiiBoard = models.ForeignKey(Board, on_delete=models.PROTECT, related_name='xiiStudents', verbose_name='XII Board')
    yearOfPassingXii = models.SmallIntegerField(verbose_name='Year Of Passing XII')

    dateOfJoining = models.DateField(verbose_name='Date Of Joining')
    department = models.CharField(max_length=80, choices=DEPARTMENT)
    degree = models.ForeignKey(Degree, on_delete=models.PROTECT)
    # BATCH =[('2016','2016'),('2017','2017'),('2018','2018'),('2019','2019'),('2020','2020'),('2021','2021')]
    batch = models.SmallIntegerField(verbose_name='Batch')


    created =models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.id 


class PermanentAddress(Address):
    student = models.OneToOneField(Student, on_delete=models.CASCADE, verbose_name='Permanent Address')
    street = models.CharField(max_length=80, verbose_name='Street / House No.')

    class Meta:
        verbose_name_plural = 'Permanent Address'


class CorrespondenceAddress(Address):
    student = models.OneToOneField(Student, on_delete=models.CASCADE, verbose_name='Correspondence Address')
    street = models.CharField(max_length=80, verbose_name='Street / House No.')

    class Meta:
        verbose_name_plural = 'Correspondence Address'


class Result(models.Model):
    GRADES = [(10, 'A'), (9, 'AB'), (8, 'B'), (7, 'BC'), (6, 'C'), (4, 'D'), (0, 'F')]
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.PROTECT)
    semester = models.SmallIntegerField()
    created =models.DateTimeField(auto_now_add=True)
    grade = models.SmallIntegerField(choices=GRADES)
    noofpresents = models.FloatField(verbose_name='% No. of Presents', blank=True)
    totalclasses = models.FloatField(verbose_name='% Total classes', blank=True)

    @property
    def attendance(self):
        return round((100*self.noofpresents/self.totalclasses),2)

   
    def save(self, *args, **kwargs):
        super(Result, self).save(*args, **kwargs)
        grades = Grade.objects.filter(student=self.student).filter(semester=self.semester)
        print(grades)
        if len(grades) == 0:
            Grade(student=self.student, semester=self.semester).save()

    def __str__(self):
        return str(self.student) + ":  " + str(self.subject) + "  -  " + str(self.grade)


class Grade(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    semester = models.IntegerField()

    @property
    def sgpi(self):
        results = Result.objects.filter(student=self.student).filter(semester=self.semester)
        (scoredPoints, totalPoints, maxGrade) = (0, 0, 10)
        for result in results:
            totalPoints += result.subject.credit * maxGrade
            scoredPoints += result.subject.credit * result.grade
        if totalPoints == 0: return 0
        return round((10 * scoredPoints / totalPoints), 2)

    @property
    def cgpi(self):
        (scoredPoints, totalPoints, maxGrade) = (0, 0, 10)
        results = Result.objects.filter(student=self.student).filter(semester__lte=self.semester)
        for result in results:
            totalPoints += result.subject.credit * maxGrade
            scoredPoints += result.subject.credit * result.grade
        if totalPoints == 0: return 0
        return round((10 * scoredPoints / totalPoints), 2)

    def __str__(self):
        return str(self.student) + "  -  Semester " + str(self.semester) + ":  " + str(self.sgpi)


class Participation(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    activity = models.ForeignKey(Activity, on_delete=models.PROTECT)
    achievement = models.CharField(max_length=30, blank=True)
    created =models.DateTimeField(auto_now_add=True)
        

    @property
    def activityName(self):
        return str(self.activity.activityName)

    class Meta:
        verbose_name_plural = 'Participation'

    def __str__(self):
        return str(self.student) + "  :  " + str(self.activity)


class Placements(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name='Roll No')
    company = models.CharField(max_length=50)
    package = models.IntegerField(blank=True, verbose_name='Package')
    created =models.DateTimeField(auto_now_add=True)
    

    @property
    def department(self):
        return str(self.student.department)

    class Meta:
        verbose_name_plural = 'Placements'
    def __str__(self):
        return str(self.student) 

class Suggestions(models.Model):
    student = models.CharField(max_length=15, verbose_name='student')
    suggestions = models.TextField(max_length=250)
    GENDER = [('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')]
    gender = models.CharField(max_length=80, choices=GENDER)
    # @property
    # def gender(self):
    #     return str(self.student.gender)

   
    class Meta:
        verbose_name_plural = 'Suggestions'
    def __str__(self):
        return str(self.student)

class OtherExam(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name='Roll No')
    EXAMS = [('GATE', 'GATE'),('CAT', 'CAT'), ('UPSC', 'UPSC'),('GRE', 'GRE'), ('GMAT', 'GMAT'), ('DRDO', 'DRDO'),('ISRO', 'ISRO'), ('MAT', 'MAT'), ('NET', 'NET'),('SSB', 'SSB'), ('SBI', 'SBI'), ('IRS', 'IRS')]

    exam = models.CharField(max_length=80, choices=EXAMS,verbose_name='Exam Name')
    examRollNumber = models.CharField(max_length=15, verbose_name='Exam Roll Number',null=True)
    examAIR = models.IntegerField(verbose_name='All India Rank',null=True)
    examMarks = models.FloatField(verbose_name='Exam Score')
    yearOfAppearingexam = models.SmallIntegerField(verbose_name='Year Of Appearing',null=True)
    nooftimeexam= models.IntegerField(verbose_name='No. of attempts',null=True)


    created =models.DateTimeField(auto_now_add=True)

    @property
    def department(self):
        return str(self.student.department)
    
    class Meta:
        verbose_name_plural = 'OtherExams'
    
    def __str__(self):
        return str(self.student) 

NithAdministration/Student/views.py
from django.shortcuts import render
from .models import Student,Suggestions
from django.shortcuts import render, redirect
from django.views.generic import ListView

def index(request):
    return render(request, 'layout1.html')

def guidelines(request):
    return render(request, 'guidelines.html')

def staffguidelines(request):
    return render(request, 'staffguidelines.html')

NithAdministration/Student/templates/changes.html
{% extends "admin/change_list.html" %}
{% load staticfiles %}
{% block extrahead %}
<!-- <link rel="shortcut icon" href="/static/logo1.png" /> -->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                position: 'left'
            },
            title: {
                display: true
            },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        window.onload = function () {
            var ctx = document.getElementById("gender-chart");
            {% regroup cl.queryset|dictsort:"gender" by get_gender_display as gender_list %}
            var lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for gender in gender_list %}'{{ gender.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for gender in gender_list %}'{{ gender.list|length }}',{% endfor %}],
                        backgroundColor: [{% for gender in gender_list %}randomColorGenerator(),{% endfor %}]
                    }]
                },
                options:{
                legend: {
                              position: 'left'
                        },
                    title: {
                            display: true,
                            text: '1.Gender ratio in Nit Hamirpur'
                        }
                   }
            });
           
            ctx = document.getElementById("department-chart");
            {% regroup cl.queryset|dictsort:"department" by department as department_list %}
            var myBarChart = new Chart(ctx, {
                type: 'horizontalBar',
                data: {
                    labels: [{% for department in department_list %}'{{ department.grouper }}',{% endfor %}],
                    datasets: [{
                        label: 'No Of Students',
                        data: [{% for department in department_list %}'{{ department.list|length }}',{% endfor %}],
                        backgroundColor: [{% for department in department_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options:{
                legend: {
                              position: 'left'
                        },
                    title: {
                            display: true,
                            text: '2.No of students dept-wise'
                        }
                   }
            });
        }
    </script>
{% endblock %}
{% block content %}
      <div id="content-main">
        
      <ul class="object-tools">
    
    
    <li><a href='/Student/student/import/' class="import_link">Import</a></li>
    <li><a href="/Student/student/export/?" class="export_link">Export</a></li></ul>
  
    <h3> ANALYTICS </h3>
    <hr>
    <div class="row">
        <div class="col-sm-4">
            <canvas id="gender-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4">
            <canvas id="department-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4">
            <canvas id="grades-chart" style="width: 100px !important;"></canvas>
        </div>
    </div>
    {{ block.super }}
{% endblock %}

NithAdministration/Student/templates/changes1.html
{% extends "admin/change_list.html" %}
{% load staticfiles %}


{% block extrahead %}
<!-- <link rel="shortcut icon" href="/static/logo1.png" /> -->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                position: 'left'
            },
            title: {
                display: true
            },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        window.onload = function () {
            ctx = document.getElementById("grades-chart");
            {% regroup cl.queryset|dictsort:"grade" by grade as grade_list %}
            lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for grade in grade_list %}'{{ grade.grouper }}',{% endfor %}],
                    datasets: [{
                        
                        data: [{% for grade in grade_list %}'{{ grade.list|length }}',{% endfor %}],
                        backgroundColor: [{% for grade in grade_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options:{
                legend: {
                              position: 'left'
                        },
                    title: {
                            display: true,
                            text: '1.Grade Analysis'
                        }
                   }
            });
            
               var ctx = document.getElementById("attendance-chart");
            {% regroup cl.queryset|dictsort:"attendance" by attendance as attendance_list %}
            var lineChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [{% for attendance in attendance_list %}'{{ attendance.grouper }}',{% endfor %}],
                    datasets: [{
                        label: 'Attendance',
                        data: [{% for attendance in attendance_list %}'{{ attendance.list|length }}',{% endfor %}],
                        backgroundColor: [{% for attendance in attendance_list %}randomColorGenerator(),{% endfor %}]
                    }]
                },
                options:{
                legend: {
                              position: 'left'
                        },
                    title: {
                            display: true,
                            text: '2.Attendance Analysis'
                        }
                   }
            });
           
        }
        
    </script>
{% endblock %}
{% block content %}

<div id="content-main">
    
    <ul class="object-tools">
      
    
  
  
  
  <li><a href='/Student/result/import/' class="import_link">Import</a></li>
  
  
    
  
  
  
  <li><a href="/Student/result/export/?" class="export_link">Export</a></li> </ul>
      <h2> Analytics </h2>
 
    <hr>
    <div class="row">

        <div class="col-sm-4">
            <canvas id="grades-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4">
            <canvas id="attendance-chart" style="width: 100px !important;"></canvas>
        </div>
    </div>
    {{ block.super }}
{% endblock %}

NithAdministration/Student/templates/changes2.html
{% extends "admin/change_list.html" %}
{% load staticfiles %}
{% block extrahead %}
<!-- <link rel="shortcut icon" href="/static/logo1.png" /> -->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                position: 'left'
            },
            title: {
                display: true
            },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        window.onload = function () {
            
            var ctx = document.getElementById("student-chart");
            {% regroup cl.queryset|dictsort:"department" by department as department_list %}
            var myBarChart = new Chart(ctx, {
                type: 'horizontalBar',
                data: {
                    labels: [{% for department in department_list %}'{{ department.grouper }}',{% endfor %}],
                    datasets: [{
                        label: 'No Of Students Placed',
                        data: [{% for department in department_list %}'{{ department.list|length }}',{% endfor %}],
                        backgroundColor: [{% for department in department_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options:{
                legend: {
                              position: 'left'
                        },
                    title: {
                            display: true,
                            text: '1.Placement ratio in each department'
                        }
                   }
            });
            var ctx = document.getElementById("company-chart");
            {% regroup cl.queryset|dictsort:"company" by company as company_list %}
            var lineChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [{% for company in company_list %}'{{ company.grouper }}',{% endfor %}],
                    datasets: [{
                        label: 'company',
                        data: [{% for company in company_list %}'{{ company.list|length }}',{% endfor %}],
                        backgroundColor: [{% for company in company_list %}randomColorGenerator(),{% endfor %}]
                    }]
                },
                options:{
                legend: {
                              position: 'left'
                        },
                    title: {
                            display: true,
                            text: '2.Company-wise placement analytics'
                        }
                   }
            });
            var ctx = document.getElementById("package-chart");
            ctx.height = 70;
            {% regroup cl.queryset|dictsort:"package" by package as package_list %}
            var lineChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [{% for package in package_list %}'{{ package.grouper }}',{% endfor %}],
                    datasets: [{
                        label: 'package',
                        data: [{% for package in package_list %}'{{ package.list|length }}',{% endfor %}],
                        backgroundColor: [{% for package in package_list %}randomColorGenerator(),{% endfor %}]
                    }]
                },
                options:{
                legend: {
                              position: 'left'
                        },
                    title: {
                            display: true,
                            text: '3.Package analytics'
                        }
                   }
            });
        }
        
    </script>
{% endblock %}
{% block content %}

<div id="content-main">
    
    <ul class="object-tools">
        <li><a href='/Student/placements/import/' class="import_link">Import</a></li>        
        <li><a href="/Student/placements/export/?" class="export_link">Export</a></li>             
    </ul>

     <h2> Analytics </h2>
 
    <hr>
    <div class="row">

        <div class="col-sm-4">
            <canvas id="student-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4">
            <canvas id="company-chart" style="width: 100px !important;"></canvas>
        </div>
        
        <div class="col-sm-4">
                <canvas id="package-chart" style="width: 100px !important;"></canvas>
         </div>
            
    </div>
    {{ block.super }}
{% endblock %}

NithAdministration/Student/templates/changes5.html
{% extends "admin/change_list.html" %}
{% load staticfiles %}
{% load static %}
{% block extrahead %}
<!-- <link rel="shortcut icon" href="/static/logo1.png" /> -->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                position: 'left'
            },
            title: {
                display: true
            },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        window.onload = function () {


            var ctx = document.getElementById("gender-chart");
            {% regroup cl.queryset|dictsort:"gender" by gender as gender_list %}
            var myBarChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: [{% for gender in gender_list %}'{{ gender.grouper }}',{% endfor %}],
                    datasets: [{
                        label: 'No Of Students that give suggestion',
                        data: [{% for gender in gender_list %}'{{ gender.list|length }}',{% endfor %}],
                        backgroundColor: [{% for gender in gender_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options:{
                legend: {
                              position: 'left'
                        },
                    title: {
                            display: true,
                            text: '1.Suggestion ratio by gender'
                        }
                   }
            });
        var ctx = document.getElementById("suggestions-chart");
        ctx.height = 800;
            {% regroup cl.queryset|dictsort:"suggestions" by suggestions as suggestions_list %}
            lineChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: [{% for suggestions in suggestions_list %}'{{ suggestions.grouper }}',{% endfor %}],
                    datasets: [{
                        label: 'Suggestions',
                        data: [{% for suggestions in suggestions_list %}'{{ suggestions.list|length }}',{% endfor %}],
                        backgroundColor: [{% for suggestions in suggestions_list %}randomColorGenerator(),{% endfor %}]
                    }]
                },options:{
                legend: {
                              position: 'left'
                        },
                    title: {
                            display: true,
                            text: '2.suggestion analytics'
                        }
                   }
            });
           
        }
        
    </script>
{% endblock %}
{% block content %}
<div id="content-main">
    
        <ul class="object-tools">    
      <li><a href='/Student/suggestions/import/' class="import_link">Import</a></li>
      <li><a href="/Student/suggestions/export/?" class="export_link">Export</a></li>

        <li>
                  
    </ul>

     <h2> Analytics </h2>
 
    <hr>
    <div class="row">

        <div class="col-sm-4">
            <canvas id="gender-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4"  style="width: 500px ">
            <canvas id="suggestions-chart" style="width: 1000px !important;"></canvas>
        </div>
    </div>
    {{ block.super }}
{% endblock %}

NithAdministration/Student/templates/layout1.html
{% extends "layout.html" %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'Elective/style1.css' %}">

<h1>About Site</h1>
<hr>
<p>
        The site is for NIT Kurukshetra to keep track of their student records like personal, contact, result, placement, other exams, co-curricular activities details etc. Dynamic analytics are also present on the site.
</p>

<p>
    Following are the <b>Analytics</b> of various activities of NIT Kurukshetra Students. Use <b>Filters </b>and <b>Search</b> options according to requirements for better analytics. 
</p>

<p>
<ul>

    <li><a href=http://127.0.0.1:8000/Student/student/>Student Profile</a></li>
    <li><a href=http://127.0.0.1:8000/Student/result/>Result </a></li>
    <li><a href=http://127.0.0.1:8000/Student/placements/>Placements</a></li>
    <li><a href=http://127.0.0.1:8000/Student/otherexam/>OtherExam</a></li>
    <li><a href=http://127.0.0.1:8000/Student/suggestions/>Suggestions</a></li>


</ul>
</p>
{% endblock content %}